### ISSUE TITLE
Remove and abstract network name hardcoding

### ISSUE THREAD

**Issue by pknath19** [chef-partners/knife-vcair#23] opened 2015-01-27 17:35 UTC
root@chefdev2:/home/chefclient/chef-repo# knife vcair server create --ssh-password password --image UB# Base VM Routed --node-name UB4 --cpus 2 --memory 2048 --customization-script ./home/chefclient/chef-repo/config/install-linux-vcair.sh -VV
WARN: Unresolved specs during Gem::Specification.reset:
      nokogiri (>= 1.4.0, >= 1.5.11, ~> 1.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
DEBUG: vcair_username User.User@User.com
DEBUG: vcair_org M222222222-2222
DEBUG: vcair_api_host p3v1-vcd.vchs.vmware.com
DEBUG: vcair_api_version
DEBUG: vcair_show_progress
DEBUG: Using fog version: 1.27.0
/root/.chefdk/gem/ruby/2.1.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:148:in `instantiate': undefined method `id' for nil:NilClass (NoMethodError)
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:37:in `execute_command'
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/command.rb:51:in `run'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
        from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
        from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from /opt/chefdk/bin/knife:38:in `load'
        from /opt/chefdk/bin/knife:38:in `<main>'
root@chefdev2:/home/chefclient/chef-repo#

**Comment by cheeseplus** [comment] 2015-01-27 23:24
@pknath19 Which version of ChefDK?

**Comment by pknath19** [comment] 2015-02-11 22:36
0.4.0  Currently I just installed this on a windows box and did a gem build knife-vcair.gemspec and chef gem install knife-vcair-0.X.0.gem.  The GEM says it installs but when I look at C:\Users\nathp\.chefdk\gem\ruby\2.0.0\gems\knife-vcair-0.6.0 the director only has the LICENCE and README.md file in the directory.   

Is 0.4.0 too new?

**Comment by cheeseplus** [comment] 2015-02-12 17:53
Based on the following issue and my testing knife-vcair shouldn't work at all with ChefDK 0.4.0 without a fix:
https://github.com/chef-partners/knife-vcair/issues/20

So I'm surprised it didn't blow up on something else although if no other gems were installed it might.

I've got this PR in the works which should fix the known ChefDK/Chef 12 issues
https://github.com/chef-partners/knife-vcair/pull/25

**Comment by cheeseplus** [comment] 2015-02-14 00:17
I'm having trouble reproducing this error, for example:
```
knife vcair server create --ssh-password password --image "Ubuntu Server 12.04 LTS (amd64 20140927)" --node-name UB4 --cpus 2 --memory 2048 --customization-script install-linux-vcair-example.sh -VV
```

works entirely as expected.

I can get a similar error if I run the above command without the --image string without quotes or if the string passed doesn't match any available images.

@pknath19 
Does `knife vcair image list` have an image that matches the string you are passing to `--image` and also does quoting it fix the issue?

**Comment by pknath19** [comment] 2015-02-19 19:23
I still get the error even if I use the command with quotes. I will build a Linux VM and use that as my Devbox and see if it fixes the issue.  The only thing I can think of is there is something with my setup.  I have uninstalled and reinstalled the CHEFDK and rebuild the plugin a few times.  This is Windows 7 64 bit BTW.  Let me know if you want to troubleshoot this anymore.  

PS C:\Code\devops-lab\chef-repo> knife vcair image list
WARN: Unresolved specs during Gem::Specification.reset:
      nokogiri (>= 1.4.0, >= 1.5.11, ~> 1.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Name                                                                           Description

CentOS63-32Bit                                                                 id: cts-6.3-32bit

CentOS63-64Bit                                                                 id: cts-6.3-64bit

CentOS64-32Bit                                                                 id: cts-6.4-32bit

CentOS64-64Bit                                                                 id: cts-6.4-64bit

en_sql_server_2012_enterprise_edition_with_service_pack_2_x64_dvd_4351704-iso  SQL Enterprise 2012 R2 w/ SP2 (MSDN
)
en_windows_7_enterprise_with_sp1_x86_dvd_u_677710.iso                          MSDN

UBBase                                                                         ChefVM

Ubuntu Server 12.04 LTS (amd64 20140927)                                       id: UBUNTU1204-AMD-64BIT

Ubuntu Server 12.04 LTS (i386 20140927)                                        id: UBUNTU1204-I386-64BIT

W2K12-STD-64BIT                                                                id: W2K12-STD-64BIT

W2K12-STD-64BIT-SQL2K12-STD-SP1                                                id: W2K12-STD-64BIT-SQL2K12-STD-SP1

W2K12-STD-64BIT-SQL2K12-WEB-SP1                                                id: W2K12-STD-64BIT-SQL2K12-WEB-SP1

W2K12-STD-R2-64BIT                                                             id: W2K12-STD-R2-64BIT

W2K12-STD-R2-SQL2K14-STD                                                       id: W2K12-STD-R2-SQL2K14-STD

W2K12-STD-R2-SQL2K14-WEB                                                       id: W2K12-STD-R2-SQL2K14-WEB

W2K8-STD-R2-64BIT                                                              id: W2K8-STD-R2-64BIT

W2K8-STD-R2-64BIT-SQL2K8-STD-R2-SP2                                            id: W2K8-STD-R2-64BIT-SQL2K8-STD-R2
-SP2
W2K8-STD-R2-64BIT-SQL2K8-WEB-R2-SP2                                            id: W2K8-STD-R2-64BIT-SQL2K8-STD-R2
-SP2
WS2012R2-DC                                                                    Microsoft Windows Server 2012 R2 Da
ta Center Edition (MSDN)
PS C:\Code\devops-lab\chef-repo> knife vcair server create --ssh-password password --image "Ubuntu Server 12.04 LT
S (amd64 20140927)" --node-name UB4 --cpus 2 --memory 2048 --customization-script install-linux-vcair-example.sh -
VV
WARN: Unresolved specs during Gem::Specification.reset:
      nokogiri (>= 1.4.0, >= 1.5.11, ~> 1.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
INFO: Using configuration from C:/Code/devops-lab/chef-repo/.chef/knife.rb
DEBUG: vcair_username UserName@emc.com
DEBUG: vcair_org M1111111111-1756
DEBUG: vcair_api_host Host.vmware.com
DEBUG: vcair_api_version
DEBUG: vcair_show_progress
DEBUG: Using fog version: 1.27.0
C:/Users/nathp/.chefdk/gem/ruby/2.0.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:148:in `instant
iate': undefined method `id' for nil:NilClass (NoMethodError)
        from C:/Users/nathp/.chefdk/gem/ruby/2.0.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:37
:in `execute_command'
        from C:/Users/nathp/.chefdk/gem/ruby/2.0.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/command.rb:51:in `r
un'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:213:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:52:in `load'
        from C:/opscode/chefdk/bin/knife:52:in `<main>'

**Comment by MayankRShepHertz** [comment] 2015-03-12 10:42
i am also getting the same error while running command 
knife vcair server create   --ssh-password Password1   --image "CentOS64-64bit"   --customization-script ./install-linux-vcair.sh   --cpus 4   --memory 4096   --node-name centos64

below is the error 

DL is deprecated, please use Fiddle
WARN: Unresolved specs during Gem::Specification.reset:
      highline (>= 1.6.9, ~> 1.6)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
ERROR: knife encountered an unexpected error
This may be a bug in the 'vcair server create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `id' for nil:NilClass

please help me

**Comment by mattray** [comment] 2015-03-12 20:26
I know that @taylor and @hh are looking at knife-vcair and working on Test Kitchen and Chef Provisioning support, I'll ask them to check out the gem dependencies as they validate that knife-vcair is still working.

**Comment by cheeseplus** [comment] 2015-03-13 16:12
@pknath19 I've looked into this again and it still seems that the underlying issue is that whatever is being provided in `--image IMAGE_NAME` (reminder, this is case sensitive) doesn't exist on the vcloud air server.

@MayankRShepHertz you might be getting bit by the same thing but if you can run the command with higher verbosity `-VV` then it'll help point to where the code is dying. It would also be helpful to have the knife (Chef) version you are using `knife --version` and whether or not the ChefDK is being used.

**Comment by MayankRShepHertz** [comment] 2015-03-13 16:26
i run the command knife --version and the output is below
Chef: 12.1.1

i run the create server command with --vv and it is giving me the same 
Chef: 12.1.1


please help me and thanks for your response

**Comment by cheeseplus** [comment] 2015-03-13 16:29
@MayankRShepHertz for the knife output it's just `-VV` (one dash and capitalized)

**Comment by MayankRShepHertz** [comment] 2015-03-13 16:42
this is the output 

/usr/local/lib/ruby/gems/2.0.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:148:in `instantiate': undefined method `id' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/2.0.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:37:in `execute_command'
        from /usr/local/lib/ruby/gems/2.0.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/command.rb:51:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.rb:214:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application/knife.rb:138:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/bin/knife:25:in `<top (required)>'
        from /usr/local/bin/knife:23:in `load'
        from /usr/local/bin/knife:23:in `<main>'

**Comment by MayankRShepHertz** [comment] 2015-03-13 16:47
i used the below command posted by you but producing the same error

knife vcair server create --ssh-password password --image "Ubuntu Server 12.04 LTS (amd64 20140927)" --node-name UB4 --cpus 2 --memory 2048 --customization-script install-linux-vcair-example.sh -VV

**Comment by cheeseplus** [comment] 2015-03-13 17:06
@pknath19 @MayankRShepHertz I think I've found where this is broken:

https://github.com/chef-partners/knife-vcair/blob/bac21302ec5a8110892f07770c36d867a33233c7/lib/chef/knife/vcair_helpers.rb#L30-L34

Specifically line 33 where it appears we are searching for a specific string in the network name:
`@net ||= org.networks.find { |n| n if n.name.match("routed$") }`

To confirm, run `knife vcair network list` and I'm betting that there isn't a network with "routed" at the end of its name. It appears we noted this in comments but this explains why our testing would work fine.

**Comment by MayankRShepHertz** [comment] 2015-03-13 17:11
@cheeseplus 
you are absolutly right . i run the command to get the network and didn't find any . then what is the solution to this problem. 

Please this is really urgent

**Comment by MayankRShepHertz** [comment] 2015-03-13 17:30
@cheeseplus 
i created the network and  using knife vcair network list  i am getting network list.

but still it is giving me the same error

**Comment by mattray** [comment] 2015-03-13 17:44
@MayankRShepHertz is this a vCloud Air subscription account or On Demand?

**Comment by MayankRShepHertz** [comment] 2015-03-13 17:55
@mattray 
it is On demand account i think. what is  the difference . and how does it matter related to this issue

**Comment by cheeseplus** [comment] 2015-03-14 00:55
@MayankRShepHertz It matters because the APIs are different versions, Dedicated Cloud and Virtual Private Cloud use at 5.6 while OnDemand is 5.11. These aren't precisely the same service and as such we haven't validated against OnDemand - we currently only have access to a VPC lab.

That said, I've got a branch and opened PR  https://github.com/chef-partners/knife-vcair/pull/27 to address the stated https://github.com/chef-partners/knife-vcair/issues/23#issuecomment-79139735

@pknath19 this should also fix your issue.

**Comment by MayankRShepHertz** [comment] 2015-03-14 07:07
@cheeseplus 
i pulled the latest code from sgt-issue 23 but still i am having the same issue . Please help

knife vcair server create --ssh-password password --image "W2K8-STD-R2-64BIT" --node-name UB4 --cpus 2 --memory 2048 --customization-script install-linux-vcair-example.sh -VV
DL is deprecated, please use Fiddle
INFO: Using configuration from /root/knife.rb
DEBUG: vcair_username vchs-cert7@vmware.com
DEBUG: vcair_org M263083285-4455
DEBUG: vcair_api_host p4v15-vcd.vchs.vmware.com
DEBUG: vcair_api_version
DEBUG: vcair_show_progress
DEBUG: Using fog version: 1.28.0
/usr/local/lib/ruby/gems/2.0.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:148:in `instantiate': undefined method `id' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/2.0.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:37:in `execute_command'
        from /usr/local/lib/ruby/gems/2.0.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/command.rb:51:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.rb:214:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application/knife.rb:138:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/bin/knife:25:in `<top (required)>'
        from /usr/local/bin/knife:23:in `load'
        from /usr/local/bin/knife:23:in `<main>'

**Comment by cheeseplus** [comment] 2015-03-14 07:55
@MayankRShepHertz are you sure you're using the latest code? I changed the number of lines in vcair_server_create.rb so it doesn't make sense that the error would still be on line 148.

Try running `knife vcair server create --help | grep vcair-net`

The ouput should be
```
      --vcair-net NETWORKNAME      Your VCAIR NETWORK
```

If that output isn't present, then it's the code from my PR isn't getting executed.

**Comment by MayankRShepHertz** [comment] 2015-03-14 08:00
Yes there is no output . can you post the link from where i need to get the code .

**Comment by cheeseplus** [comment] 2015-03-14 08:17
You can use git:
```
git fetch
git checkout sgt-issue23
```

Or just snag the zip file here:
https://github.com/chef-partners/knife-vcair/archive/sgt-issue23.zip

**Comment by MayankRShepHertz** [comment] 2015-03-14 09:19
@cheeseplus 
i did the same but still it is giving me no output on running knife vcair server create --help | grep vcair-net 
 and giving error on running server create command

**Comment by cheeseplus** [comment] 2015-03-14 17:11
@MayankRShepHertz how are you installing / executing the gem?

If knife can't find the sub-command then the gem is not installed correctly. You may have to uninstall, build, and then install it or use Bundler.

For example, on my system it requires:
```
gem uninstall knife-vcair
gem build knife-vcair.gemspec
gem install knife-vcair-0.7.0.gem
```

You could also use a rake subcommands
```
rake clobber_package
rake uninstall
rake install
```

If using Bundler you don't even need to compile the gem as it can execute from source in cwd, so this would execute the command:
```
bundle exec knife vcair server list
```

**Comment by MayankRShepHertz** [comment] 2015-03-14 19:24
@cheeseplus 

hi i am getting below error now

knife vcair server create --ssh-password password --image "W2K8-STD-R2-64BIT-SQL2K8-STD-R2-SP2" --node-name UB4 --cpus 2 --memory 2048 --customization-script install-linux-vcair-example.sh
DL is deprecated, please use Fiddle

ERROR: Fog::Compute::VcloudDirector::BadRequest: [ 17a8c0e9-0438-454b-b808-205bd7479f4a ] The VCD entity UB4 already exists.

if i do -VV then below then is the output

/usr/local/lib/ruby/gems/2.0.0/gems/excon-0.44.4/lib/excon/middlewares/expects.rb:6:in `response_call': [ 851c3213-e596-434e-82da-acf1419cf41d ] The VCD entity UB4 already exists. (Fog::Compute::VcloudDirector::BadRequest)
        from /usr/local/lib/ruby/gems/2.0.0/gems/excon-0.44.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
        from /usr/local/lib/ruby/gems/2.0.0/gems/excon-0.44.4/lib/excon/connection.rb:372:in `response'
        from /usr/local/lib/ruby/gems/2.0.0/gems/excon-0.44.4/lib/excon/connection.rb:236:in `request'
        from /usr/local/lib/ruby/gems/2.0.0/gems/fog-xml-0.1.1/lib/fog/xml/sax_parser_connection.rb:37:in `request'
        from /usr/local/lib/ruby/gems/2.0.0/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:7:in `request'
        from /usr/local/lib/ruby/gems/2.0.0/gems/fog-1.28.0/lib/fog/vcloud_director/compute.rb:402:in `do_request'
        from /usr/local/lib/ruby/gems/2.0.0/gems/fog-1.28.0/lib/fog/vcloud_director/compute.rb:372:in `request'
        from /usr/local/lib/ruby/gems/2.0.0/gems/fog-1.28.0/lib/fog/vcloud_director/requests/compute/instantiate_vapp_template.rb:24:in `instantiate_vapp_template'
        from /usr/local/lib/ruby/gems/2.0.0/gems/fog-1.28.0/lib/fog/vcloud_director/models/compute/catalog_item.rb:16:in `instantiate'
        from /usr/local/lib/ruby/gems/2.0.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:144:in `instantiate'
        from /usr/local/lib/ruby/gems/2.0.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_server_create.rb:36:in `execute_command'
        from /usr/local/lib/ruby/gems/2.0.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/command.rb:51:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.rb:214:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application/knife.rb:138:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/bin/knife:25:in `<top (required)>'
        from /usr/local/bin/knife:23:in `load'
 
i am really thank ful for your help

**Comment by MayankRShepHertz** [comment] 2015-03-14 19:32
if i remove --node-name  UB4 and run below command knife vcair server create --ssh-password password --image "Ubuntu Server 12.04 LTS (amd64 20150127)"  --cpus 2 --memory 2048 --customization-script install-linux-vcair-example.sh

then get the below error

ERROR: Errno::ENOENT: No such file or directory - install-linux-vcair-example.sh

**Comment by cheeseplus** [comment] 2015-03-14 22:40
@MayankRShepHertz the values provided in the examples are just that - examples. You will need to point the command at the path (full or relative) of your desired customization script

If you are in the directory of this knife-air repository then you could use:
```
knife vcair server create --ssh-password password --image "Ubuntu Server 12.04 LTS (amd64 20150127)" --node-name UB1 --cpus 2 --memory 2048 --customization-script ./install-linux-vcair-example.sh
```

Otherwise it's expected that you use a script of your own crafting at a path of your choosing.

**Comment by pknath19** [comment] 2015-03-24 17:16
@cheeseplus @MayankRShepHertz  Thanks for figuring out this issue.   I was out of the country for a few weeks glad you both figured it out.  I knew something was wrong.  I see the pull request was made.   Has it been merged to master or should I pull sgt-issue23?

**Comment by cheeseplus** [comment] 2015-03-24 17:36
@pknath19 going to merge to master shortly (positive this fixes the biggest issue) and then push to RubyGems - for the moment you can pull and test this branch.

**Comment by cheeseplus** [comment] 2015-03-24 19:12
Merged to master @ https://github.com/chef-partners/knife-vcair/pull/27

**Comment by cheeseplus** [comment] 2015-03-24 21:07
@pknath19 merged to master and released to RubyGems at 0.6.1 - will leave issue open until I get confirmation the fix works for others

**Comment by pknath19** [comment] 2015-03-24 21:57
@cheeseplus I am able to create VM's with the updated code.  Just having a few issues with knife connecting to the VM over SSH.  Where do I configure the NAT IP and Port?  in the Script?  Otherwise you fixed my creation of the VM now it just needs to connect to bootstrap the VM.

**Comment by cheeseplus** [comment] 2015-03-24 22:13
@pknath19 currently the API doesn't expose a way to associate NAT IP and port to a vApp so we didn't build in any support for it - this means that you need to use an ssh-gateway to a machine on the same network or run knife directly from a machine on the same network.

For example, I use:

```
knife vcair server create --ssh-password Password1 --image "CentOS64-64BIT" --customization-script ./install-linux-vcair-example.sh --cpus 4 --memory 2048 --node-name 4-t --vcair-show-progress true --vcair-net M511664989-4904-default-routed --ssh-gateway cheeseplus@BASTION
```

Where `BASTION` is the public IP that is already mapped to a VM on the same network as the host I am creating. The `knife-ec2` plugin has the ` --server-connect-attribute ATTRIBUTE` option which we'll probably copy in this plugin if/when the API supports it.

**Comment by cheeseplus** [comment] 2015-03-24 22:58
Closing this out as the reported issue has been fixed, feel free to open new issues.

**Closed by cheeseplus** 2015-03-24 22:58 UTC
