### ISSUE TITLE
create server error

### ISSUE THREAD

**Issue by MayankRShepHertz** [chef-partners/knife-vcair#26] opened 2015-03-12 11:33 UTC
i am also getting the same error while running command 
knife vcair server create --ssh-password Password1 --image "CentOS64-64bit" --customization-script ./install-linux-vcair.sh --cpus 4 --memory 4096 --node-name centos64

below is the error

DL is deprecated, please use Fiddle
WARN: Unresolved specs during Gem::Specification.reset:
highline (>= 1.6.9, ~> 1.6)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
ERROR: knife encountered an unexpected error
This may be a bug in the 'vcair server create' knife command or plugin
Please collect the output of this command with the -VV option before filing a bug report.
Exception: NoMethodError: undefined method `id' for nil:NilClass

please help me

**Comment by cheeseplus** [comment] 2015-03-13 00:12
Closing as a dupe of #23

**Closed** 2015-03-13 00:12 UTC

**Comment by MayankRShepHertz** [comment] 2015-03-13 05:50
Thanks cheeseplus, i refered the above #23  but i did not get it what the fix you provide . 
i am using chef 11 version and linuz 12 please help me   this is really urgent.

**Comment by MayankRShepHertz** [comment] 2015-03-13 05:54
Hi,

Mine issue is not fixed yet. i am still not able to create VM using create
command. i am using linux 12 version and chef 11 version.

Please help me on this .

**Comment by cheeseplus** [comment] 2015-03-13 16:17
@MayankRShepHertz I closed this issue because an issue for this has already been opened and you've already commented on it. Duplicate issues just make for more noise. As stated in the other thread, folks will be looking at this soon.
